image:
  file: .gitpod.Dockerfile

tasks:
  - name: reset lamdera
    command: sudo yes | lamdera reset
    
  - name: start lamdera server
    init: gp sync-await lamdera
    command: sudo lamdera live
ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - elmtooling.elm-ls-vscode
    - hbenl.vscode-test-explorer
    - hbenl.test-adapter-converter
