image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install
    command: npm start
  - command: elm-language-server
  - command: lamdera reset | y
ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - elmtooling.elm-ls-vscode
